name: CI Pipeline

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

# Environment variables (fallback for local act)
env:
  REGISTRY: ghcr.io/kkarri0119          # Change to your Docker Hub or GHCR username
  IMAGE_NAME: springboot-product-microservice
  GITHUB_SHA: ${{ github.sha || 'localtest001' }}  # fallback SHA for act
  KUBE_NAMESPACE: default

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Install Maven
      run: |
        apt-get update
        apt-get install -y maven

    - name: Build Spring Boot Product Microservices
      run: mvn clean install

    - name: Log in to GitHub Container Registry
      if: github.actor != 'local'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME || 'placeholder' }}
        password: ${{ secrets.DOCKER_PASSWORD || 'placeholder' }}
        registry: ghcr.io

    #Build Docker Image
    #- name: Build Docker Image
    #  run: |
    #    echo "Building Docker image..."
    #    docker build -t $REGISTRY/$IMAGE_NAME:$GITHUB_SHA .
    #    docker push $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
    - name: Build and Push Docker Image
      if: github.actor != 'local'
      run: |
        docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME }}/springboot-product-microservice:${GITHUB_SHA} .
        docker push ghcr.io/${{ secrets.DOCKER_USERNAME }}/springboot-product-microservice:${GITHUB_SHA}

    #Deploy to Kubernetes
    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v3
      with:
        manifests: k8s/deployment.yaml
        images: $REGISTRY/$IMAGE_NAME:$GITHUB_SHA
        namespace: $KUBE_NAMESPACE

